{{- if and .Values.runner.enabled (and (empty .Values.runner.configMapOverrideName) (empty .Values.runner.configFromSecret)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "runner.labels" . | nindent 4 }}
  name: {{ template "runner.fullname" . }}
{{ include "runner.namespace" . | indent 2 }}
data:
{{- $root := . -}}
{{- range $key, $value := .Values.runnerFiles }}
  {{- if $key | regexMatch ".*\\.ya?ml$" }}
  {{ $key }}: |
{{ toYaml $value | default "{}" | indent 4 }}
  {{- else }}
  {{ $key }}: {{ toYaml $value | indent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
