apiVersion: v1
kind: Service
metadata:
  name: {{ include "fuse.fullname" . }}-graphql
spec:
  selector:
    fuse-component: graphql
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5433
