apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fuse.fullname" . }}
  labels:
    {{- include "fuse.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fuse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fuse.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fuse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-worker-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: [/usr/local/bin/migrate]
          args: ["-database", "$(POSTGRES_CONNECTION)", "-path", "migrations", "up"]
          env:
            - name: POSTGRES_CONNECTION
              value: postgres://postgres:password@fuse-postgresql:5432/postgres?sslmode=disable
          {{- if .Values.fuse.envFrom }}
          envFrom: {{- include "common.tplvalues.render" (dict "value" .Values.fuse.envFrom "context" $ ) | nindent 12 }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # TODO(patrickdevivo) implement health checks in worker
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CONCURRENCY
              value: {{ .Values.fuse.config.concurrency | quote }}
            - name: POSTGRES_CONNECTION
              value: postgres://postgres:password@fuse-postgresql:5432/postgres # default if none is supplied, assumes pg is running with default values as well
          {{- if .Values.fuse.envFrom }}
          envFrom: {{- include "common.tplvalues.render" (dict "value" .Values.fuse.envFrom "context" $ ) | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
